name: jaxrl5
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.2
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=69.5.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - clarabel==0.7.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cvxpy==1.4.3
      - cycler==0.12.1
      - decorator==4.4.2
      - distrax==0.1.5
      - dm-control==1.0.18
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - ecos==2.0.13
      - etils==1.5.2
      - eval-type-backport==0.2.0
      - farama-notifications==0.0.4
      - flax==0.8.2
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gym==0.24.0
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - idna==3.7
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - lxml==5.2.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - moviepy==1.0.3
      - msgpack==1.0.8
      - mujoco==3.1.4
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - opt-einsum==3.3.0
      - optax==0.2.2
      - orbax-checkpoint==0.5.9
      - osqp==0.6.5
      - packaging==24.0
      - pillow==10.3.0
      - proglog==0.1.10
      - protobuf==4.25.3
      - psutil==5.9.8
      - pybind11==2.12.0
      - pygame==2.5.2
      - pygments==2.17.2
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - qdldl==0.1.7.post1
      - requests==2.31.0
      - rich==13.7.1
      - scipy==1.11.4
      - scs==3.2.4.post1
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - tensorflow-probability==0.17.0
      - tensorstore==0.1.56
      - toolz==0.12.1
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - tyro==0.8.3
      - urllib3==2.2.1
      - wandb==0.16.6
      - zipp==3.18.1
